version: '3.7'

services:
  caddy: 
    image: caddy:2.4.5-alpine
    env_file: .env
    volumes:
      - caddy:/caddy-storage
      - ./caddy/http.Caddyfile:/etc/caddy/Caddyfile
      # Uncomment the following line when using HTTPS with Let's Encrypt's staging environment
      # - './caddy/https.lets-encrypt-staging.Caddyfile:/etc/caddy/Caddyfile'
      #
      # Uncomment the following line when using HTTPS with Let's Encrypt's production environment
      # IMPORTANT: Strongly recommended to test with the staging configuration above first, see that file for details.
      # - './caddy/https.lets-encrypt-prod.Caddyfile:/etc/caddy/Caddyfile'
    ports:
      - '127.0.0.1:80:80'
      # Uncomment when working in staging/prod
      # - '0.0.0.0:80:80'
      # Uncomment when using HTTPS
      # - '0.0.0.0:443:443'
    networks:
      - sg-learn
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    env_file: .env
    ports: '3001:3001'
    networks:
      - sg-learn
    restart: unless-stopped

networks:
  sg-learn:

volumes:
  caddy:
